[package]
name = "defuss-langid"
version = "0.0.1"
edition = "2021"
publish = false
description = "Extremely fast, small and accurate language detection for the web, written in Rust and compiled to WebAssembly."
license = "MIT"
authors = ["Aron Homberg <info@aron-homberg.de>"]
keywords = [
    "language-detection",
    "wasm",
    "multicore",
    "rust",
    "javascript",
    "typescript",
    "webassembly",
    "browser",
    "web-workers"
  ]
repository = "https://github.com/kyr0/defuss"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-rayon = "1.3"
wasm-bindgen-futures = "0.4"
rayon = "1.10"
console_error_panic_hook = "0.1.2"
web-sys = { version = "0.3", features = [
  'console',
  'Performance'
] }
js-sys = { version = "0.3" }
gloo-timers =  { version = "0.3", features = ["futures"] }

byteorder = "1.5"
ndarray = { version = "0.16", default-features = false, features=["std"] }
thiserror  = "2.0"

[package.metadata.wasm-pack.profile.dev]
wasm-opt = ["-O4", "--enable-threads", "--enable-bulk-memory", "--enable-simd"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "--enable-threads", "--enable-bulk-memory", "--enable-simd"]