import { existsSync, readFileSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const run = (command: string, cwd: string = root) => {
  console.log(`\n> ${command}`);
  execSync(command, { cwd, stdio: "inherit" });
};

const hasCommand = (command: string): boolean => {
  try {
    execSync(`${command} --version`, { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
};

// Clean previous output
rmSync(join(root, "dist"), { recursive: true, force: true });
rmSync(join(root, "wasm", "pkg"), { recursive: true, force: true });

// Build compressor WASM
run(
  "wasm-pack build --release --target bundler --out-dir ../../wasm/pkg/compressor .",
  join(root, "rust", "compressor"),
);

// Build decompressor WASM
run(
  "wasm-pack build --release --target bundler --out-dir ../../wasm/pkg/decompressor .",
  join(root, "rust", "decompressor"),
);

// Optimize WASM with wasm-opt if available
if (hasCommand("wasm-opt")) {
  const wasmFiles = [
    join(root, "wasm", "pkg", "compressor", "defuss_brotli_compressor_bg.wasm"),
    join(root, "wasm", "pkg", "decompressor", "defuss_brotli_decompressor_bg.wasm"),
  ];
  for (const wasmFile of wasmFiles) {
    if (existsSync(wasmFile)) {
      run(`wasm-opt -Oz -o ${wasmFile} ${wasmFile}`);
    }
  }
}

// --- Inline WASM as base64 into self-contained dist modules ---

mkdirSync(join(root, "dist"), { recursive: true });

/**
 * Reads a wasm-bindgen _bg.js glue file and strips the `import * as wasm`
 * line and the `__wbg_set_wasm` export. Instead, we provide `wasm` via
 * instantiation and wire it up ourselves.
 */
function readGlueCode(bgJsPath: string): string {
  let code = readFileSync(bgJsPath, "utf-8");
  // Remove the bare `let wasm;` and the `__wbg_set_wasm` setter — we assign wasm directly
  code = code.replace(/\blet\s+wasm\s*;\s*\n?/, "");
  code = code.replace(/export\s+function\s+__wbg_set_wasm\(val\)\s*\{[^}]*\}\s*\n?/, "");
  return code;
}

/**
 * Builds a self-contained ESM dist file that:
 * 1. Embeds the WASM binary as base64
 * 2. On init(), decodes base64 → ArrayBuffer → WebAssembly.instantiate
 * 3. Wires up the wasm-bindgen glue (the _bg.js code)
 * 4. Re-exports the TS-level API (compress/decompress, etc.)
 */
function buildInlinedModule(config: {
  name: string;
  wasmPath: string;
  bgJsPath: string;
  srcTsPath: string;
  outPath: string;
  exportedWasmFn: string;
}) {
  const wasmBytes = readFileSync(config.wasmPath);
  const wasmBase64 = wasmBytes.toString("base64");
  const wasmSize = wasmBytes.length;
  const glueCode = readGlueCode(config.bgJsPath);

  console.log(`\n  ${config.name}: ${wasmSize} bytes WASM → ${wasmBase64.length} chars base64`);

  // Read the source TS and compile it via bun build to get the JS
  // But we want to replace the dynamic import with our inline init
  // Instead, we build the whole module from scratch using the glue + our TS API

  // Read the TS source to extract the API code (everything except the init body)
  const srcTs = readFileSync(config.srcTsPath, "utf-8");

  // Build a self-contained ESM module
  const output = `// Auto-generated by scripts/build.ts — DO NOT EDIT
// ${config.name} with inlined WASM (${wasmSize} bytes)

// --- Base64 WASM binary ---
const WASM_BASE64 = "${wasmBase64}";

function decodeBase64ToArrayBuffer(base64) {
  if (typeof atob === "function") {
    const binStr = atob(base64);
    const bytes = new Uint8Array(binStr.length);
    for (let i = 0; i < binStr.length; i++) bytes[i] = binStr.charCodeAt(i);
    return bytes.buffer;
  }
  // Node.js fallback
  return new Uint8Array(Buffer.from(base64, "base64")).buffer;
}

// --- wasm-bindgen glue (from _bg.js, with wasm variable) ---
let wasm;
${glueCode}

// --- Public API ---

${config.name === "compressor" ? `
var DEFAULT_QUALITY = 6;
var DEFAULT_LGWIN = 22;
var initPromise = null;
var ready = false;
var wasmCompressBytes = null;

function assertReady() {
  if (!ready || !wasmCompressBytes) {
    throw new Error("defuss-brotli/compressor is not initialized. Call await init() first.");
  }
}

function normalizeOptions(options = {}) {
  const quality = options.quality ?? DEFAULT_QUALITY;
  const lgwin = options.lgwin ?? DEFAULT_LGWIN;
  if (!Number.isInteger(quality) || quality < 0 || quality > 11) {
    throw new Error("quality must be an integer between 0 and 11");
  }
  if (!Number.isInteger(lgwin) || lgwin < 10 || lgwin > 24) {
    throw new Error("lgwin must be an integer between 10 and 24");
  }
  return { quality, lgwin };
}

async function init() {
  if (!initPromise) {
    initPromise = (async () => {
      const wasmBuffer = decodeBase64ToArrayBuffer(WASM_BASE64);
      const wasmModule = await WebAssembly.compile(wasmBuffer);
      const imports = {};
      // wasm-bindgen bundler target uses __wbindgen_cast_0000000000000001
      imports["./defuss_brotli_compressor_bg.js"] = { __wbindgen_cast_0000000000000001 };
      const instance = await WebAssembly.instantiate(wasmModule, imports);
      wasm = instance.exports;
      wasmCompressBytes = compress_bytes;
      ready = true;
    })();
  }
  return initPromise;
}

function isReady() {
  return ready;
}

function compress(input, options = {}) {
  assertReady();
  const { quality, lgwin } = normalizeOptions(options);
  return wasmCompressBytes(input, quality, lgwin);
}

function compressText(text, options = {}) {
  return compress(new TextEncoder().encode(text), options);
}

export { DEFAULT_QUALITY, DEFAULT_LGWIN, assertReady, normalizeOptions, init, isReady, compress, compressText };
` : `
var DEFAULT_MAX_OUTPUT_SIZE = 64 * 1024 * 1024;
var initPromise = null;
var ready = false;
var wasmDecompressBytes = null;

function assertReady() {
  if (!ready || !wasmDecompressBytes) {
    throw new Error("defuss-brotli/decompressor is not initialized. Call await init() first.");
  }
}

function normalizeOptions(options = {}) {
  const maxOutputSize = options.maxOutputSize ?? DEFAULT_MAX_OUTPUT_SIZE;
  if (!Number.isInteger(maxOutputSize) || maxOutputSize <= 0) {
    throw new Error("maxOutputSize must be a positive integer");
  }
  return { maxOutputSize };
}

async function init() {
  if (!initPromise) {
    initPromise = (async () => {
      const wasmBuffer = decodeBase64ToArrayBuffer(WASM_BASE64);
      const wasmModule = await WebAssembly.compile(wasmBuffer);
      const imports = {};
      imports["./defuss_brotli_decompressor_bg.js"] = { __wbindgen_cast_0000000000000001 };
      const instance = await WebAssembly.instantiate(wasmModule, imports);
      wasm = instance.exports;
      wasmDecompressBytes = decompress_bytes;
      ready = true;
    })();
  }
  return initPromise;
}

function isReady() {
  return ready;
}

function decompress(input, options = {}) {
  assertReady();
  const { maxOutputSize } = normalizeOptions(options);
  return wasmDecompressBytes(input, maxOutputSize);
}

function decompressText(input, options = {}) {
  return new TextDecoder().decode(decompress(input, options));
}

export { DEFAULT_MAX_OUTPUT_SIZE, wasmDecompressBytes, assertReady, normalizeOptions, init, isReady, decompress, decompressText };
`}
`;

  writeFileSync(config.outPath, output, "utf-8");
  console.log(`  → ${config.outPath}`);
}

buildInlinedModule({
  name: "compressor",
  wasmPath: join(root, "wasm/pkg/compressor/defuss_brotli_compressor_bg.wasm"),
  bgJsPath: join(root, "wasm/pkg/compressor/defuss_brotli_compressor_bg.js"),
  srcTsPath: join(root, "src/compressor.ts"),
  outPath: join(root, "dist/compressor.js"),
  exportedWasmFn: "compress_bytes",
});

buildInlinedModule({
  name: "decompressor",
  wasmPath: join(root, "wasm/pkg/decompressor/defuss_brotli_decompressor_bg.wasm"),
  bgJsPath: join(root, "wasm/pkg/decompressor/defuss_brotli_decompressor_bg.js"),
  srcTsPath: join(root, "src/decompressor.ts"),
  outPath: join(root, "dist/decompressor.js"),
  exportedWasmFn: "decompress_bytes",
});

// Generate .d.ts declarations
run("bunx tsc --project tsconfig.build.json");
