[package]
name = "defuss-fastmath"
version = "0.0.1"
edition = "2021"
publish = false
description = "Ludicrously fast multicore math for Rust, JavaScript, TypeScript, browsers, and Node.js"
license = "MIT"
authors = ["Aron Homberg <info@aron-homberg.de>"]
keywords = [
    "fastmath", 
    "math", 
    "wasm",
    "multicore",
    "rust",
    "javascript",
    "typescript",
    "nodejs",
    "browser",
    "audio",
    "dsp",
    "ml",
    "matmul",
    "oscillators"
  ]
repository = "https://github.com/kyr0/defuss"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-rayon = "1.2"
wasm-bindgen-futures = "0.4"
rayon = "1.8"
console_error_panic_hook = "0.1.2"
web-sys = { version = "0.3", features = [
  'console',
  'Performance'
] }
js-sys = { version = "0.3" }
gloo-timers =  { version = "0.3", features = ["futures"] }

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
# Tell `rustc` to optimize for performance
opt-level = 3
lto = true
codegen-units = 1