import type { ReplacementRule } from "./types.js";

export const REPLACEMENT_RULES: readonly ReplacementRule[] = [
  // Dashes / hyphens
  { match: "—", replacement: "-", description: "em dash" },
  { match: "–", replacement: "-", description: "en dash" },
  { match: "‒", replacement: "-", description: "figure dash" },
  { match: "―", replacement: "--", description: "horizontal bar" },
  { match: "‐", replacement: "-", description: "hyphen" },
  { match: "-", replacement: "-", description: "non-breaking hyphen" },
  { match: "⁃", replacement: "-", description: "hyphen bullet" },
  { match: "﹘", replacement: "-", description: "small em dash" },
  { match: "﹣", replacement: "-", description: "small hyphen-minus" },
  { match: "－", replacement: "-", description: "fullwidth hyphen-minus" },
  { match: "−", replacement: "-", description: "minus sign" },
  { match: "⎯", replacement: "-", description: "horizontal line extension" },
  { match: "⏤", replacement: "--", description: "straight horizontal bar" },
  {
    match: "─",
    replacement: "-",
    description: "box drawings light horizontal",
  },
  {
    match: "━",
    replacement: "-",
    description: "box drawings heavy horizontal",
  },
  { match: "╴", replacement: "-", description: "box drawings light left" },
  { match: "╶", replacement: "-", description: "box drawings light right" },
  { match: "᠆", replacement: "-", description: "mongolian todo soft hyphen" },
  { match: "֊", replacement: "-", description: "hebrew maqaf" },
  {
    match: "゠",
    replacement: "-",
    description: "katakana-hiragana double hyphen",
  },

  // Arrows
  { match: "→", replacement: "=>", description: "right arrow" },
  { match: "⟶", replacement: "=>", description: "long right arrow" },
  { match: "➜", replacement: "=>", description: "heavy right arrow" },
  { match: "➔", replacement: "=>", description: "black right arrow" },
  { match: "➝", replacement: "=>", description: "drafting right arrow" },
  { match: "➡", replacement: "=>", description: "black rightwards arrow" },
  { match: "⇢", replacement: "=>", description: "rightwards dashed arrow" },
  { match: "⇨", replacement: "=>", description: "rightwards white arrow" },
  { match: "⇒", replacement: "=>", description: "double right arrow" },
  { match: "⟹", replacement: "=>", description: "long double right arrow" },
  {
    match: "⇛",
    replacement: "=>",
    description: "rightwards triple dash arrow",
  },

  { match: "←", replacement: "<=", description: "left arrow" },
  { match: "⟵", replacement: "<=", description: "long left arrow" },
  { match: "⇐", replacement: "<=", description: "double left arrow" },
  { match: "⟸", replacement: "<=", description: "long double left arrow" },
  { match: "⬅", replacement: "<=", description: "black leftwards arrow" },

  { match: "↔", replacement: "<->", description: "left right arrow" },
  {
    match: "⇄",
    replacement: "<->",
    description: "right arrow over left arrow",
  },
  {
    match: "⇆",
    replacement: "<->",
    description: "left arrow over right arrow",
  },
  { match: "⇔", replacement: "<=>", description: "left right double arrow" },
  { match: "⟷", replacement: "<->", description: "long left right arrow" },
  {
    match: "⟺",
    replacement: "<=>",
    description: "long left right double arrow",
  },

  { match: "↑", replacement: "^", description: "up arrow" },
  { match: "⇑", replacement: "^^", description: "double up arrow" },
  { match: "↓", replacement: "v", description: "down arrow" },
  { match: "⇓", replacement: "vv", description: "double down arrow" },
  { match: "↕", replacement: "^v", description: "up down arrow" },
  { match: "⇕", replacement: "^^vv", description: "up down double arrow" },

  // Bullets / markers
  { match: "✔", replacement: "-", description: "heavy check mark" },
  { match: "✅", replacement: "-", description: "check mark button" },
  { match: "☑", replacement: "-", description: "ballot box with check" },
  { match: "✓", replacement: "-", description: "check mark" },
  { match: "🗸", replacement: "-", description: "light check mark" },
  { match: "✗", replacement: "x", description: "ballot x" },
  { match: "✘", replacement: "x", description: "heavy ballot x" },
  { match: "✕", replacement: "x", description: "multiplication x" },
  { match: "✖", replacement: "x", description: "heavy multiplication x" },

  { match: "•", replacement: "-", description: "bullet" },
  { match: "‣", replacement: "-", description: "triangular bullet" },
  { match: "◦", replacement: "-", description: "white bullet" },
  { match: "▪", replacement: "-", description: "small square bullet" },
  { match: "▫", replacement: "-", description: "small white square" },
  { match: "■", replacement: "-", description: "black square" },
  { match: "□", replacement: "-", description: "white square" },
  {
    match: "▸",
    replacement: "-",
    description: "black right-pointing small triangle",
  },
  {
    match: "▹",
    replacement: "-",
    description: "white right-pointing small triangle",
  },
  { match: "►", replacement: "-", description: "black right-pointing pointer" },
  { match: "▻", replacement: "-", description: "white right-pointing pointer" },
  { match: "●", replacement: "-", description: "black circle bullet" },
  { match: "○", replacement: "-", description: "white circle bullet" },
  { match: "◉", replacement: "-", description: "fisheye" },
  { match: "◎", replacement: "-", description: "bullseye" },
  { match: "◯", replacement: "-", description: "large circle" },
  { match: "·", replacement: "-", description: "middle dot" },
  { match: "・", replacement: "-", description: "katakana middle dot" },
  { match: "∙", replacement: "*", description: "bullet operator" },
  { match: "⋅", replacement: "*", description: "dot operator" },
  { match: "‧", replacement: "-", description: "hyphenation point" },
  { match: "※", replacement: "-", description: "reference mark" },
  { match: "⁂", replacement: "***", description: "asterism" },
  { match: "❖", replacement: "-", description: "black diamond minus white x" },
  { match: "◆", replacement: "-", description: "black diamond" },
  { match: "◇", replacement: "-", description: "white diamond" },
  {
    match: "◈",
    replacement: "-",
    description: "white diamond containing black small diamond",
  },
  {
    match: "❥",
    replacement: "-",
    description: "rotated heavy black heart bullet",
  },

  // Quotes / apostrophes / primes
  { match: "“", replacement: '"', description: "left double quote" },
  { match: "”", replacement: '"', description: "right double quote" },
  { match: "„", replacement: '"', description: "low double quote" },
  { match: "‟", replacement: '"', description: "double high-reversed-9 quote" },
  { match: "«", replacement: '"', description: "left guillemet" },
  { match: "»", replacement: '"', description: "right guillemet" },
  { match: "‹", replacement: "'", description: "left single guillemet" },
  { match: "›", replacement: "'", description: "right single guillemet" },
  { match: "‘", replacement: "'", description: "left single quote" },
  {
    match: "’",
    replacement: "'",
    description: "right single quote / apostrophe",
  },
  { match: "‚", replacement: "'", description: "low single quote" },
  { match: "‛", replacement: "'", description: "single high-reversed-9 quote" },
  {
    match: "❛",
    replacement: "'",
    description: "heavy left single quote ornament",
  },
  {
    match: "❜",
    replacement: "'",
    description: "heavy right single quote ornament",
  },
  {
    match: "❝",
    replacement: '"',
    description: "heavy left double quote ornament",
  },
  {
    match: "❞",
    replacement: '"',
    description: "heavy right double quote ornament",
  },
  { match: "〝", replacement: '"', description: "reversed double prime quote" },
  { match: "〞", replacement: '"', description: "double prime quote" },
  { match: "＂", replacement: '"', description: "fullwidth quotation mark" },
  { match: "＇", replacement: "'", description: "fullwidth apostrophe" },
  { match: "′", replacement: "'", description: "prime" },
  { match: "‵", replacement: "'", description: "reversed prime" },
  { match: "ʹ", replacement: "'", description: "modifier letter prime" },
  { match: "ʻ", replacement: "'", description: "modifier letter turned comma" },
  { match: "ʼ", replacement: "'", description: "modifier letter apostrophe" },
  {
    match: "ʽ",
    replacement: "'",
    description: "modifier letter reversed comma",
  },
  {
    match: "ʾ",
    replacement: "'",
    description: "modifier letter right half ring",
  },
  {
    match: "ʿ",
    replacement: "'",
    description: "modifier letter left half ring",
  },
  {
    match: "ˈ",
    replacement: "'",
    description: "modifier letter vertical line",
  },
  { match: "ˊ", replacement: "'", description: "modifier letter acute accent" },
  { match: "ˋ", replacement: "'", description: "modifier letter grave accent" },
  {
    match: "˴",
    replacement: "'",
    description: "modifier letter middle grave accent",
  },
  { match: "´", replacement: "'", description: "acute accent" },
  { match: "`", replacement: "'", description: "grave accent" },

  { match: "″", replacement: '""', description: "double prime" },
  { match: "‶", replacement: '""', description: "reversed double prime" },
  {
    match: "ʺ",
    replacement: '""',
    description: "modifier letter double prime",
  },
  { match: "‴", replacement: '"""', description: "triple prime" },
  { match: "⁗", replacement: '""""', description: "quadruple prime" },

  // Ellipsis / dots
  { match: "…", replacement: "...", description: "ellipsis" },
  { match: "‥", replacement: "..", description: "two dot leader" },
  {
    match: "⋯",
    replacement: "...",
    description: "midline horizontal ellipsis",
  },
  {
    match: "︙",
    replacement: "...",
    description: "presentation form for vertical horizontal ellipsis",
  },
  { match: "⋮", replacement: ":", description: "vertical ellipsis" },
  { match: "⋰", replacement: "...", description: "up right diagonal ellipsis" },
  {
    match: "⋱",
    replacement: "...",
    description: "down right diagonal ellipsis",
  },

  // Math / relations
  { match: "≤", replacement: "<=", description: "less-than-or-equal" },
  { match: "≦", replacement: "<=", description: "less-than over equal" },
  {
    match: "⩽",
    replacement: "<=",
    description: "slanted equal to or less-than",
  },
  { match: "≥", replacement: ">=", description: "greater-than-or-equal" },
  { match: "≧", replacement: ">=", description: "greater-than over equal" },
  {
    match: "⩾",
    replacement: ">=",
    description: "slanted equal to greater-than",
  },
  { match: "≠", replacement: "!=", description: "not-equal" },
  { match: "≉", replacement: "!=", description: "not almost equal" },
  { match: "≈", replacement: "~=", description: "almost equal" },
  { match: "≃", replacement: "~=", description: "asymptotically equal" },
  { match: "≅", replacement: "~=", description: "approximately equal" },
  { match: "∼", replacement: "~", description: "tilde operator" },
  { match: "∽", replacement: "~", description: "reversed tilde" },
  { match: "∿", replacement: "~", description: "sine wave" },
  { match: "˜", replacement: "~", description: "small tilde" },
  { match: "〜", replacement: "~", description: "wave dash" },
  { match: "～", replacement: "~", description: "fullwidth tilde" },
  { match: "≪", replacement: "<<", description: "much less-than" },
  { match: "≫", replacement: ">>", description: "much greater-than" },
  { match: "⋘", replacement: "<<", description: "very much less-than" },
  { match: "⋙", replacement: ">>", description: "very much greater-than" },
  { match: "¬", replacement: "!", description: "not sign" },
  { match: "±", replacement: "+/-", description: "plus-minus" },
  { match: "∓", replacement: "-/+", description: "minus-or-plus" },
  { match: "×", replacement: "*", description: "multiplication sign" },
  { match: "÷", replacement: "/", description: "division sign" },
  { match: "⁄", replacement: "/", description: "fraction slash" },
  { match: "∕", replacement: "/", description: "division slash" },
  { match: "∣", replacement: "|", description: "divides" },
  { match: "∥", replacement: "||", description: "parallel to" },
  { match: "¦", replacement: "|", description: "broken bar" },
  { match: "‖", replacement: "||", description: "double vertical line" },
  { match: "∧", replacement: "^", description: "logical and" },
  { match: "∨", replacement: "v", description: "logical or" },
  { match: "⊕", replacement: "+", description: "circled plus" },
  { match: "⊗", replacement: "*", description: "circled times" },
  { match: "⊙", replacement: ".", description: "circled dot" },
  { match: "√", replacement: "sqrt", description: "square root" },
  { match: "∛", replacement: "cuberoot", description: "cube root" },
  { match: "∞", replacement: "inf", description: "infinity" },
  { match: "∈", replacement: "in", description: "element of" },
  { match: "∉", replacement: "not in", description: "not element of" },
  { match: "∅", replacement: "{}", description: "empty set" },
  { match: "∩", replacement: "cap", description: "intersection" },
  { match: "∪", replacement: "cup", description: "union" },
  { match: "⊂", replacement: "<", description: "subset of" },
  { match: "⊃", replacement: ">", description: "superset of" },
  { match: "⊆", replacement: "<=", description: "subset of or equal" },
  { match: "⊇", replacement: ">=", description: "superset of or equal" },
  { match: "∴", replacement: "therefore", description: "therefore" },
  { match: "∵", replacement: "because", description: "because" },

  // Fractions
  {
    match: "¼",
    replacement: "1/4",
    description: "vulgar fraction one quarter",
  },
  { match: "½", replacement: "1/2", description: "vulgar fraction one half" },
  {
    match: "¾",
    replacement: "3/4",
    description: "vulgar fraction three quarters",
  },
  {
    match: "⅐",
    replacement: "1/7",
    description: "vulgar fraction one seventh",
  },
  { match: "⅑", replacement: "1/9", description: "vulgar fraction one ninth" },
  { match: "⅒", replacement: "1/10", description: "vulgar fraction one tenth" },
  { match: "⅓", replacement: "1/3", description: "vulgar fraction one third" },
  { match: "⅔", replacement: "2/3", description: "vulgar fraction two thirds" },
  { match: "⅕", replacement: "1/5", description: "vulgar fraction one fifth" },
  { match: "⅖", replacement: "2/5", description: "vulgar fraction two fifths" },
  {
    match: "⅗",
    replacement: "3/5",
    description: "vulgar fraction three fifths",
  },
  {
    match: "⅘",
    replacement: "4/5",
    description: "vulgar fraction four fifths",
  },
  { match: "⅙", replacement: "1/6", description: "vulgar fraction one sixth" },
  {
    match: "⅚",
    replacement: "5/6",
    description: "vulgar fraction five sixths",
  },
  { match: "⅛", replacement: "1/8", description: "vulgar fraction one eighth" },
  {
    match: "⅜",
    replacement: "3/8",
    description: "vulgar fraction three eighths",
  },
  {
    match: "⅝",
    replacement: "5/8",
    description: "vulgar fraction five eighths",
  },
  {
    match: "⅞",
    replacement: "7/8",
    description: "vulgar fraction seven eighths",
  },

  // Symbols
  { match: "©", replacement: "(c)", description: "copyright sign" },
  { match: "®", replacement: "(r)", description: "registered sign" },
  { match: "℗", replacement: "(p)", description: "sound recording copyright" },
  { match: "™", replacement: "TM", description: "trade mark sign" },
  { match: "℠", replacement: "SM", description: "service mark" },
  { match: "°", replacement: " deg", description: "degree sign" },
  { match: "℃", replacement: " degC", description: "degree celsius" },
  { match: "℉", replacement: " degF", description: "degree fahrenheit" },
  { match: "№", replacement: "No.", description: "numero sign" },
  { match: "ª", replacement: "a", description: "feminine ordinal indicator" },
  { match: "º", replacement: "o", description: "masculine ordinal indicator" },
  { match: "‰", replacement: "permille", description: "per mille sign" },
  {
    match: "‱",
    replacement: "permyriad",
    description: "per ten thousand sign",
  },

  // Spaces / invisibles / separators
  { match: "\u00A0", replacement: " ", description: "no-break space" },
  { match: "\u1680", replacement: " ", description: "ogham space mark" },
  { match: "\u2000", replacement: " ", description: "en quad" },
  { match: "\u2001", replacement: " ", description: "em quad" },
  { match: "\u2002", replacement: " ", description: "en space" },
  { match: "\u2003", replacement: " ", description: "em space" },
  { match: "\u2004", replacement: " ", description: "three-per-em space" },
  { match: "\u2005", replacement: " ", description: "four-per-em space" },
  { match: "\u2006", replacement: " ", description: "six-per-em space" },
  { match: "\u2007", replacement: " ", description: "figure space" },
  { match: "\u2008", replacement: " ", description: "punctuation space" },
  { match: "\u2009", replacement: " ", description: "thin space" },
  { match: "\u200A", replacement: " ", description: "hair space" },
  { match: "\u202F", replacement: " ", description: "narrow no-break space" },
  {
    match: "\u205F",
    replacement: " ",
    description: "medium mathematical space",
  },
  { match: "\u3000", replacement: " ", description: "ideographic space" },

  { match: "\u00AD", replacement: "", description: "soft hyphen" },
  { match: "\u200B", replacement: "", description: "zero-width space" },
  { match: "\u200C", replacement: "", description: "zero-width non-joiner" },
  { match: "\u200D", replacement: "", description: "zero-width joiner" },
  { match: "\u2060", replacement: "", description: "word joiner" },
  { match: "\u2061", replacement: "", description: "function application" },
  { match: "\u2062", replacement: "", description: "invisible times" },
  { match: "\u2063", replacement: "", description: "invisible separator" },
  { match: "\u2064", replacement: "", description: "invisible plus" },
  {
    match: "\u206A",
    replacement: "",
    description: "inhibit symmetric swapping",
  },
  {
    match: "\u206B",
    replacement: "",
    description: "activate symmetric swapping",
  },
  {
    match: "\u206C",
    replacement: "",
    description: "inhibit arabic form shaping",
  },
  {
    match: "\u206D",
    replacement: "",
    description: "activate arabic form shaping",
  },
  { match: "\u206E", replacement: "", description: "national digit shapes" },
  { match: "\u206F", replacement: "", description: "nominal digit shapes" },
  { match: "\uFEFF", replacement: "", description: "byte-order mark" },
  {
    match: "\u034F",
    replacement: "",
    description: "combining grapheme joiner",
  },
  {
    match: "\u180E",
    replacement: "",
    description: "mongolian vowel separator",
  },

  {
    match: "\r\n",
    replacement: "\n",
    description: "carriage return + line feed",
  },
  { match: "\u2028", replacement: "\n", description: "line separator" },
  { match: "\u2029", replacement: "\n\n", description: "paragraph separator" },
  { match: "\u000B", replacement: "\n", description: "vertical tab" },
  { match: "\u000C", replacement: "\n", description: "form feed" },

  // Slashes / bars
  { match: "／", replacement: "/", description: "fullwidth solidus" },
  { match: "⧸", replacement: "/", description: "big solidus" },
  {
    match: "╱",
    replacement: "/",
    description: "box drawings light diagonal upper right to lower left",
  },
  { match: "⟋", replacement: "/", description: "mathematical rising diagonal" },

  { match: "＼", replacement: "\\", description: "fullwidth reverse solidus" },
  { match: "∖", replacement: "\\", description: "set minus" },
  { match: "⧵", replacement: "\\", description: "reverse solidus operator" },
  {
    match: "⟍",
    replacement: "\\",
    description: "mathematical falling diagonal",
  },
  {
    match: "╲",
    replacement: "\\",
    description: "box drawings light diagonal upper left to lower right",
  },

  { match: "｜", replacement: "|", description: "fullwidth vertical line" },
  { match: "ǀ", replacement: "|", description: "latin letter dental click" },
  {
    match: "︱",
    replacement: "|",
    description: "presentation form for vertical em dash",
  },
  { match: "│", replacement: "|", description: "box drawings light vertical" },
  { match: "┃", replacement: "|", description: "box drawings heavy vertical" },
  {
    match: "┆",
    replacement: "|",
    description: "box drawings light triple dash vertical",
  },
  {
    match: "┊",
    replacement: "|",
    description: "box drawings light quadruple dash vertical",
  },
  {
    match: "╎",
    replacement: "|",
    description: "box drawings light double dash vertical",
  },
  {
    match: "╏",
    replacement: "|",
    description: "box drawings heavy double dash vertical",
  },

  // Punctuation
  { match: "：", replacement: ":", description: "fullwidth colon" },
  { match: "∶", replacement: ":", description: "ratio" },
  {
    match: "ː",
    replacement: ":",
    description: "modifier letter triangular colon",
  },
  { match: "꞉", replacement: ":", description: "modifier letter colon" },

  { match: "；", replacement: ";", description: "fullwidth semicolon" },

  { match: "，", replacement: ",", description: "fullwidth comma" },
  { match: "、", replacement: ",", description: "ideographic comma" },
  { match: "﹐", replacement: ",", description: "small comma" },
  { match: "﹑", replacement: ",", description: "small ideographic comma" },

  { match: "．", replacement: ".", description: "fullwidth full stop" },
  { match: "。", replacement: ".", description: "ideographic full stop" },
  {
    match: "｡",
    replacement: ".",
    description: "halfwidth ideographic full stop",
  },

  { match: "！", replacement: "!", description: "fullwidth exclamation mark" },
  { match: "‼", replacement: "!!", description: "double exclamation mark" },
  { match: "⁉", replacement: "?!", description: "exclamation question mark" },

  { match: "？", replacement: "?", description: "fullwidth question mark" },
  { match: "⁇", replacement: "??", description: "double question mark" },
  { match: "⁈", replacement: "!?", description: "question exclamation mark" },

  // Brackets
  { match: "（", replacement: "(", description: "fullwidth left parenthesis" },
  { match: "）", replacement: ")", description: "fullwidth right parenthesis" },
  {
    match: "［",
    replacement: "[",
    description: "fullwidth left square bracket",
  },
  {
    match: "］",
    replacement: "]",
    description: "fullwidth right square bracket",
  },
  {
    match: "｛",
    replacement: "{",
    description: "fullwidth left curly bracket",
  },
  {
    match: "｝",
    replacement: "}",
    description: "fullwidth right curly bracket",
  },

  { match: "〈", replacement: "<", description: "left angle bracket" },
  { match: "〉", replacement: ">", description: "right angle bracket" },
  { match: "《", replacement: "<<", description: "left double angle bracket" },
  { match: "》", replacement: ">>", description: "right double angle bracket" },
  {
    match: "⟨",
    replacement: "<",
    description: "mathematical left angle bracket",
  },
  {
    match: "⟩",
    replacement: ">",
    description: "mathematical right angle bracket",
  },

  { match: "「", replacement: "[", description: "left corner bracket" },
  { match: "」", replacement: "]", description: "right corner bracket" },
  { match: "『", replacement: "[", description: "left white corner bracket" },
  { match: "』", replacement: "]", description: "right white corner bracket" },
  {
    match: "【",
    replacement: "[",
    description: "left black lenticular bracket",
  },
  {
    match: "】",
    replacement: "]",
    description: "right black lenticular bracket",
  },
  { match: "〔", replacement: "[", description: "left tortoise shell bracket" },
  {
    match: "〕",
    replacement: "]",
    description: "right tortoise shell bracket",
  },
  {
    match: "〖",
    replacement: "[",
    description: "left white lenticular bracket",
  },
  {
    match: "〗",
    replacement: "]",
    description: "right white lenticular bracket",
  },
  {
    match: "〘",
    replacement: "[",
    description: "left white tortoise shell bracket",
  },
  {
    match: "〙",
    replacement: "]",
    description: "right white tortoise shell bracket",
  },
  { match: "〚", replacement: "[", description: "left white square bracket" },
  { match: "〛", replacement: "]", description: "right white square bracket" },

  // Misc ASCII lookalikes
  { match: "＆", replacement: "&", description: "fullwidth ampersand" },
  { match: "＊", replacement: "*", description: "fullwidth asterisk" },
  { match: "＿", replacement: "_", description: "fullwidth low line" },
  { match: "‗", replacement: "_", description: "double low line" },
  { match: "＾", replacement: "^", description: "fullwidth circumflex accent" },
  { match: "‸", replacement: "^", description: "caret insertion point" },
  { match: "％", replacement: "%", description: "fullwidth percent" },
  { match: "＋", replacement: "+", description: "fullwidth plus" },
  { match: "＝", replacement: "=", description: "fullwidth equals" },
] as const;

export const REPLACEMENT_RULE_MAP = new Map(
  REPLACEMENT_RULES.map((rule) => [rule.match, rule.replacement] as const),
);
